repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-ast
    - id: debug-statements
    - id: check-added-large-files

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
    - id: codespell
      exclude: >
          (?x)^(
              .*\.c|
              tools/fix_wrapped_ufunc_typos\.py|
              gsw/tests/test_gibbs\.py
          )$
      args:
        - --ignore-words-list=nin,preformed,wih,

- repo: https://github.com/tox-dev/pyproject-fmt
  rev: 1.8.0
  hooks:
    - id: pyproject-fmt


- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.3.7
  hooks:
    - id: ruff

ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: false
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: monthly
    skip: []
    submodules: false
