environment:
  matrix:
    - TARGET_ARCH: x64
      CONDA_PY: 35
      CONDA_NPY: 111
      CONDA_INSTALL_LOCN: C:\\Miniconda35-x64

    - TARGET_ARCH: x64
      CONDA_PY: 35
      CONDA_NPY: 112
      CONDA_INSTALL_LOCN: C:\\Miniconda35-x64

    - TARGET_ARCH: x64
      CONDA_PY: 36
      CONDA_NPY: 111
      CONDA_INSTALL_LOCN: C:\\Miniconda36-x64

    - TARGET_ARCH: x64
      CONDA_PY: 36
      CONDA_NPY: 112
      CONDA_INSTALL_LOCN: C:\\Miniconda36-x64

platform:
    - x64

install:
    # If there is a newer build queued for the same PR, cancel this one.
    # The AppVeyor 'rollout builds' option is supposed to serve the same
    # purpose but it is problematic because it tends to cancel builds pushed
    # directly to master instead of just PR builds (or the converse).
    - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
         https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
         Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
           throw "There are newer queued builds for this pull request, failing early." }

    # Add path, activate `conda` and update conda.
    - cmd: set "PATH=%CONDA_INSTALL_LOCN%\\Scripts;%CONDA_INSTALL_LOCN%\\Library\\bin;%PATH%"
    - cmd: conda update --yes --quiet conda
    - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat

    - cmd: set PYTHONUNBUFFERED=1

    - cmd: conda config --set show_channel_urls true
    - cmd: conda install --yes conda-build
    - cmd: conda info

# Skip .NET project specific build phase.
build: off

test_script:
    - "conda build conda.recipe"
