package:
  name: gsw
  version: {{ GIT_DESCRIBE_TAG|replace("v","") }}

source:
  path: ../

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
  run:
    - python
    - numpy x.x

test:
  source_files:
    - gsw/tests
  requires:
    - pytest
  imports:
    - gsw
    - gsw.ice
  commands:
    - cd gsw && py.test -s -rxs -v tests
