package:
  name: gsw
  version: 0.5.0

source:
  path: ../

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
  run:
    - python
    - numpy x.x

test:
  imports:
    - gsw
    - gsw.ice
  commands:
    - python -c "import gsw; print(dir(gsw))"
