name: windows-wheels

on:
  release:
    types:
      - published

jobs:
  packages:
    name: Build wheel on ${{ matrix.os }} and ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Get tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      shell: bash

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip wheel setuptools setuptools_scm pep517 twine
        python -m pip install numpy==1.18
      shell: bash

    - name: Build binary wheel
      run: python -m pep517.build --binary . --out-dir dist

    - name: CheckFiles
      run: |
        ls dist
      shell: bash

    - name: Test wheels
      run: |
        python -m pip install wheel twine
        python -m pip install pytest numpy
        cd dist && python -m pip install gsw*.whl && python -m pytest --pyargs gsw
        python -m twine check *
      shell: bash

    - name: upload wheel
      uses: actions/upload-artifact@v1
      with:
        name: dist_${{ matrix.os }}_${{ matrix.python-version }}
        path: dist
